/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevolucaoRouteImport } from './routes/devolucao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmprestimosIndexRouteImport } from './routes/emprestimos.index'
import { Route as EmprestimosNovoRouteImport } from './routes/emprestimos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucaoRoute = DevolucaoRouteImport.update({
  id: '/devolucao',
  path: '/devolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosIndexRoute = EmprestimosIndexRouteImport.update({
  id: '/emprestimos/',
  path: '/emprestimos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosNovoRoute = EmprestimosNovoRouteImport.update({
  id: '/emprestimos/novo',
  path: '/emprestimos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devolucao': typeof DevolucaoRoute
  '/login': typeof LoginRoute
  '/emprestimos/novo': typeof EmprestimosNovoRoute
  '/emprestimos/': typeof EmprestimosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devolucao': typeof DevolucaoRoute
  '/login': typeof LoginRoute
  '/emprestimos/novo': typeof EmprestimosNovoRoute
  '/emprestimos': typeof EmprestimosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devolucao': typeof DevolucaoRoute
  '/login': typeof LoginRoute
  '/emprestimos/novo': typeof EmprestimosNovoRoute
  '/emprestimos/': typeof EmprestimosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/devolucao' | '/login' | '/emprestimos/novo' | '/emprestimos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devolucao' | '/login' | '/emprestimos/novo' | '/emprestimos'
  id:
    | '__root__'
    | '/'
    | '/devolucao'
    | '/login'
    | '/emprestimos/novo'
    | '/emprestimos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevolucaoRoute: typeof DevolucaoRoute
  LoginRoute: typeof LoginRoute
  EmprestimosNovoRoute: typeof EmprestimosNovoRoute
  EmprestimosIndexRoute: typeof EmprestimosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucao': {
      id: '/devolucao'
      path: '/devolucao'
      fullPath: '/devolucao'
      preLoaderRoute: typeof DevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos/': {
      id: '/emprestimos/'
      path: '/emprestimos'
      fullPath: '/emprestimos/'
      preLoaderRoute: typeof EmprestimosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos/novo': {
      id: '/emprestimos/novo'
      path: '/emprestimos/novo'
      fullPath: '/emprestimos/novo'
      preLoaderRoute: typeof EmprestimosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevolucaoRoute: DevolucaoRoute,
  LoginRoute: LoginRoute,
  EmprestimosNovoRoute: EmprestimosNovoRoute,
  EmprestimosIndexRoute: EmprestimosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
